[PATH]
# 待处理图片文件夹路径
input_dir = ./input_images
# 底图路径
base_image = ./base_image/base.png
# 输出文件夹路径
output_dir = ./output_images
# 额外叠加的图片路径
# overlay_image_path = ./overlay/overlay.png
# 新指定的正片叠底图片路径
batch_overlay_image = ./overlay/batch_overlay.png

[PROCESS]
# 图片到边缘的距离（像素）
margin = 0
# 输出图片格式
output_format = png
# 需要叠加额外图片的序号（第N张，从1开始）
# target_index = 18
# 是否启用正片叠底混合模式（true/false）
multiply_blend = true
# 每个文件夹下需要应用批量叠加的最后N张图片数量
batch_overlay_count = 1